### ISSUE TITLE
strip: true を指定すると空白を含むカラムで落ちる

### ISSUE THREAD

**Issue by tmtm** [ruby/csv#115]
`strip: true` を指定すると空白を含むカラムで落ちます。

```
% ruby -rcsv -e 'CSV.parse(" v v ", strip: true)'
Traceback (most recent call last):
	7: from -e:1:in `<main>'
	6: from /home/tommy/gems26/gems/csv-3.1.2/lib/csv.rb:686:in `parse'
	5: from /home/tommy/gems26/gems/csv-3.1.2/lib/csv.rb:1289:in `read'
	4: from /home/tommy/gems26/gems/csv-3.1.2/lib/csv.rb:1289:in `to_a'
	3: from /home/tommy/gems26/gems/csv-3.1.2/lib/csv.rb:1280:in `each'
	2: from /home/tommy/gems26/gems/csv-3.1.2/lib/csv.rb:1280:in `each'
	1: from /home/tommy/gems26/gems/csv-3.1.2/lib/csv/parser.rb:334:in `parse'
/home/tommy/gems26/gems/csv-3.1.2/lib/csv/parser.rb:931:in `parse_quotable_robust': TODO: Meaningful message in line 1. (CSV::MalformedCSVError)
```

**Comment by kou** [comment]
そうかぁ、これでしっぱいしますかぁ。
修正しました。
