### ISSUE TITLE
CSV.generateのencodingにCP932を渡しても、暗黙にUTF-8とあることがある

### ISSUE THREAD

**Issue by babatakao** [ruby/csv#118]
### 概要

`CSV.generate` に `CP932` を指定し、範囲外の文字を与えた場合、暗黙のうちにUTF-8に変換されることがあります。

### 確認バージョン

ruby 2.7.0p0

### 期待動作

rubydocから正確な仕様を読み取れなかったのですが、CP932を指定して範囲外文字を渡したら、 `Encoding::CompatibilityError` が発生するのが期待動作かと思います。

### 実際の動作

手前の行にCP932範囲内のマルチバイト文字（？）が含まれていれば、範囲外文字を渡した時点でエラーになりますが、そうでない場合UTF-8に変換されてエラーは発生しません。

### 再現手順

以下の手順で、1個目（Windows-31J）と4個目（例外発生）は想像通りなのですが、2個目と3個目では暗黙にUTF-8に変換されています。

```
irb(main):001:0> require 'csv'
=> true

irb(main):002:0> CSV.generate(encoding:'CP932'){|c| c<<['テスト']}.encoding
=> #<Encoding:Windows-31J>

irb(main):003:0> CSV.generate(encoding:'CP932'){|c| c<<['テスト🍣']}.encoding
=> #<Encoding:UTF-8>

irb(main):004:0> CSV.generate(encoding:'CP932'){|c| c<<['a']; c<<['テスト🍣']}.encoding
=> #<Encoding:UTF-8>

irb(main):005:0> CSV.generate(encoding:'CP932'){|c| c<<['テスト']; c<<['テスト🍣']}.encoding
Traceback (most recent call last):
       10: from /home/baba/.rbenv/versions/2.7.0/bin/irb:23:in `<main>'
        9: from /home/baba/.rbenv/versions/2.7.0/bin/irb:23:in `load'
        8: from /home/baba/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
        7: from (irb):5
        6: from /home/baba/.rbenv/versions/2.7.0/lib/ruby/2.7.0/csv.rb:544:in `generate'
        5: from (irb):5:in `block in irb_binding'
        4: from /home/baba/.rbenv/versions/2.7.0/lib/ruby/2.7.0/csv.rb:1230:in `<<'
        3: from /home/baba/.rbenv/versions/2.7.0/lib/ruby/2.7.0/csv/writer.rb:53:in `<<'
        2: from /home/baba/.rbenv/versions/2.7.0/lib/ruby/2.7.0/csv/writer.rb:53:in `<<'
        1: from /home/baba/.rbenv/versions/2.7.0/lib/ruby/2.7.0/csv/writer.rb:53:in `write'
Encoding::CompatibilityError (incompatible character encodings: Windows-31J and UTF-8)
```

これは意図された仕様なのでしょうか？

**Comment by kou** [comment]
これはStringIOの問題なので https://github.com/ruby/stringio に報告してもらえますか？

```ruby
require "stringio"

p (StringIO.new.set_encoding("cp932") << "あ").string.encoding
p (StringIO.new.set_encoding("cp932") << "あ🍣").string.encoding
p (StringIO.new.set_encoding("cp932") << "🍣").string.encoding
p (StringIO.new.set_encoding("cp932") << "あ" << "🍣").string.encoding
```
```console
$ ruby -v /tmp/c.rb
ruby 2.8.0dev (2020-03-22T19:19:24Z master dec0f582e4) [x86_64-linux]
#<Encoding:Windows-31J>
#<Encoding:UTF-8>
#<Encoding:UTF-8>
Traceback (most recent call last):
	2: from /tmp/c.rb:6:in `<main>'
	1: from /tmp/c.rb:6:in `<<'
/tmp/c.rb:6:in `write': incompatible character encodings: Windows-31J and UTF-8 (Encoding::CompatibilityError)
```
