### ISSUE TITLE
skip_lines payload difference across verions

### ISSUE THREAD

**Issue by simi** [ruby/csv#194]
Hello.

In our project we are using following strategy to skip some lines having only `,` content.

```ruby
CSV.open(file, 'r', skip_lines: /^,+$/)
```

During update to Ruby 2.7 some specs related to this failed since it wasn't skipping lines properly. I have found out the difference is that RegExp is matched against whole line now including newline character for example. I was able to bisect the problem to https://github.com/ruby/csv/commit/39da059c6d363136a80867a6cdb7f2ac42e48ecc using this reproducing script:

```ruby
require 'test/unit'
require 'timeout'
require_relative '../../lib/csv'
class TestCSVRegress < Test::Unit::TestCase
  def setup
    super
    @sample_data = <<-CSV
line,1,abc
line,2,"def\nghi"

line,4,jkl
    CSV
  end

  def test_line_trash
    csv = CSV.new(@sample_data, :skip_lines => Class.new do
      $lines = []
      def self.match(line)
        $lines << line
      end
    end
                 )

    Timeout.timeout(0.1) do # this is needed to bandaid infinite loop bug in some csv versions
      csv.count # do something to iterate over the file

      assert_equal($lines, ["line,1,abc", "line,2,\"def", "ghi\"", "line,4,jkl"])
    end
  end
end
```

This spec is passing at v3.0.1 tag, but fails on current master with 

```
[retro@retro  csv (master $%=)]❤ ruby -Itest test/csv/test_regress.rb 
Loaded suite test/csv/test_regress
Started
F
==============================================================================================================================================================================================
test/csv/test_regress.rb:25:in `test_line_trash'
     22:     end
     23:                  )
     24: 
  => 25:     timeout(0.1) do
     26:       csv.count # do something to iterate over the file
     27: 
     28:       assert_equal($lines, ["line,1,abc", "line,2,\"def", "ghi\"", "line,4,jkl"])
/home/retro/.rubies/ruby-2.5.7/lib/ruby/2.5.0/timeout.rb:122:in `timeout'
/home/retro/.rubies/ruby-2.5.7/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
/home/retro/.rubies/ruby-2.5.7/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/home/retro/.rubies/ruby-2.5.7/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/home/retro/.rubies/ruby-2.5.7/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
/home/retro/.rubies/ruby-2.5.7/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
test/csv/test_regress.rb:28:in `block in test_line_trash'
<["line,1,abc\n", "line,2,\"def\n", "ghi\"\n", "\n", "line,4,jkl\n"]> expected but was
<["line,1,abc", "line,2,\"def", "ghi\"", "line,4,jkl"]>

diff:
? ["line,1,abc\n", "line,2,\"def\n", "ghi\"\n", "\n", "line,4,jkl\n"]
Failure: test_line_trash(TestCSVRegress)
==============================================================================================================================================================================================

Finished in 0.005389607 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 tests, 1 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
185.54 tests/s, 185.54 assertions/s
```

For now I have introduced custom class to strip the "payload" and do the check on top of that.

```ruby
class Skipper
  EMPTY_LINE = /^,+$/.freeze

  def match(line)
    line.strip.match?(EMPTY_LINE)
  end
end

CSV.open(file, mode, skip_lines: Skipper.new)
```

Anyway this seems like side-effect of mentioned change and unwanted behaviour change. I suggest to at least add spec for the payload, but I'm not sure which behaviour is intended (with/without newline character included).

**Comment by kou** [comment]
`/^,+$/` matches to both `",\n"` and `","`:

```ruby
p(/^,+$/.match?(",\n")) # -> true
p(/^,+$/.match?(","))   # -> true
```

Are you really using `/^,+$/`?

**Comment by simi** [comment]
@kou Yes.

Feel free to try with this testing file.

https://gofile.io/d/91CkpE

Using **v3.0.1** CSV with **Ruby 2.5.7** in csv repo root:

```ruby
irb(main):001:0> require_relative 'lib/csv'
=> true
irb(main):002:0> CSV.open('test-organizations.csv', 'r', {headers: true, skip_blanks: true, skip_lines: /^,+$/}).map(&:itself).count
=> 16
```

Using **v3.0.1** CSV with **Ruby 2.7.2** in csv repo root:

```ruby
irb(main):001:0> require_relative 'lib/csv'
=> true
irb(main):002:0> CSV.open('test-organizations.csv', 'r', {headers: true, skip_blanks: true, skip_lines: /^,+$/}).map(&:itself).count
/home/retro/code/work/FUGA/git/csv/lib/csv.rb:652: warning: Using the last argument as keyword parameters is deprecated
=> 16
```

Using **master** CSV with **Ruby 2.7.2** in csv repo root:

```ruby
irb(main):001:0> require_relative 'lib/csv'
=> true
irb(main):002:0> CSV.open('test-organizations.csv', 'r', {headers: true, skip_blanks: true, skip_lines: /^,+$/}).map(&:itself).count
=> 44
```

Using **master** CSV with **Ruby 2.5.7** in csv repo root:

```ruby
irb(main):001:0> require_relative 'lib/csv'
=> true
irb(main):002:0> CSV.open('test-organizations.csv', 'r', {headers: true, skip_blanks: true, skip_lines: /^,+$/}).map(&:itself).count
=> 44
```

**Comment by kou** [comment]
Ah, you're using `"\r\n"`.
Fixed.

**Comment by simi** [comment]
@kou thanks for the fix. I can confirm it works now.
