### ISSUE TITLE
#eof? raise CSV::MalformedCSVError

### ISSUE THREAD

**Issue by krororo** [ruby/csv#86]
The same code as #82. `#eof?` raise CSV::MalformedCSVError. Expected behavior returns `true` or `false` value.

backtrace:

```
$ ruby /tmp/csv.rb 
3.0.9
#<CSV::Row "head1":"head1" "head2":"head2" "head3":"head3">
#<CSV::Row "head1":"aaa" "head2":"bbb" "head3":"ccc">
Traceback (most recent call last):
	7: from /tmp/csv.rb:1:in `each'
	6: from /home/krororo/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/csv-3.0.9/lib/csv/parser.rb:303:in `parse'
	5: from /home/krororo/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/csv-3.0.9/lib/csv/parser.rb:779:in `parse_quotable_loose'
	4: from /home/krororo/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/csv-3.0.9/lib/csv/parser.rb:28:in `each_line'
	3: from /home/krororo/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/csv-3.0.9/lib/csv/parser.rb:28:in `each_line'
	2: from /home/krororo/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/csv-3.0.9/lib/csv/parser.rb:31:in `block in each_line'
	1: from /home/krororo/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/csv-3.0.9/lib/csv/parser.rb:818:in `block in parse_quotable_loose'
/home/krororo/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/csv-3.0.9/lib/csv/parser.rb:879:in `parse_quotable_robust': Illegal quoting in line 3. (CSV::MalformedCSVError)
```

**Comment by kou** [comment]
Oh, sorry!
