### ISSUE TITLE
Parsing lines with trailing whitespaces. (CSV::MalformedCSVError (Any value after quoted field isn't allowed in line 1.))

### ISSUE THREAD

**Issue by dotnofoolin** [ruby/csv#91]
When trying to parse a file that contains extra whitespace at the end of the line, the parser fails with `CSV::MalformedCSVError (Any value after quoted field isn't allowed in line 1.)`

Other programs (Numbers, OpenOffice, etc) seem to have no trouble with the file.

CSV gem version: 3.1.0

Ruby version: 2.5.1

File contents (note that there is one extra whitespace after the double quote of header_2: 
```
"header_1","header_2" 
"value_1","value_2" 
```

```
$ irb
2.5.1 :001 > require 'csv'
 => true
2.5.1 :002 > csv = CSV.open('bad_file.csv', headers: true)
 => <#CSV io_type:File io_path:"bad_file.csv" encoding:UTF-8 lineno:0 col_sep:"," row_sep:"\n" quote_char:"\"" headers:true>
2.5.1 :003 > csv.each { |row| puts row.inspect }
Traceback (most recent call last):
       11: from .rvm/rubies/ruby-2.5.1/bin/irb:11:in '<main>'
       10: from (irb):3
        9: from .rvm/gems/ruby-2.5.1/gems/csv-3.1.0/lib/csv.rb:1243:in 'each'
        8: from .rvm/gems/ruby-2.5.1/gems/csv-3.1.0/lib/csv.rb:1243:in 'each'
        7: from .rvm/gems/ruby-2.5.1/gems/csv-3.1.0/lib/csv/parser.rb:303:in 'parse'
        6: from .rvm/gems/ruby-2.5.1/gems/csv-3.1.0/lib/csv/parser.rb:779:in 'parse_quotable_loose'
        5: from .rvm/gems/ruby-2.5.1/gems/csv-3.1.0/lib/csv/parser.rb:28:in 'each_line'
        4: from .rvm/gems/ruby-2.5.1/gems/csv-3.1.0/lib/csv/parser.rb:28:in 'each_line'
        3: from .rvm/gems/ruby-2.5.1/gems/csv-3.1.0/lib/csv/parser.rb:31:in 'block in each_line'
        2: from .rvm/gems/ruby-2.5.1/gems/csv-3.1.0/lib/csv/parser.rb:818:in 'block in parse_quotable_loose'
        1: from .rvm/gems/ruby-2.5.1/gems/csv-3.1.0/lib/csv/parser.rb:869:in 'parse_quotable_robust'
CSV::MalformedCSVError (Any value after quoted field isn't allowed in line 1.)
```

**Comment by kou** [comment]
Use `CSV.open("bad_file.csv", headers: true, liberal_parsing: true)`.
